"""
pipeline.py

Orchestrates the full research pipeline:

  load prices -> build features -> walk-forward folds -> fit/predict each fold
      -> pool out-of-sample predictions across all folds
      -> compute IC per model (+ regime-conditioned IC)
      -> backtest each model's ranking score, plus benchmarks
      -> SHAP explainability on the final (most data-rich) fold's model

The single most important property of this pipeline: every prediction used
in evaluation is genuinely out-of-sample -- generated by a model trained
only on data strictly before the date being predicted (see walk_forward.py
and features.py's lookahead tests). Nothing here is fit once on the full
dataset and evaluated on the same data it was trained on.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from backtest import BacktestResult, run_backtest
from benchmarks import equal_weight_market_return, momentum_scores
from data_loader import DEFAULT_UNIVERSE, load_panel
from evaluation import ICResult, compute_ic, compute_regime_ic
from features import FEATURE_COLUMNS, build_feature_panel
from models import fit_and_predict_fold
from shap_analysis import compute_shap_importance
from walk_forward import generate_folds, split_fold


@dataclass
class PipelineResult:
    predictions: pd.DataFrame  # pooled out-of-sample predictions, all folds, all models
    ic_results: dict[str, ICResult]
    regime_ic_results: dict[str, dict[str, ICResult]]
    backtest_results: dict[str, BacktestResult]
    shap_importance: pd.DataFrame
    n_folds_run: int


def run_pipeline(
    tickers: list[str] | None = None,
    start: str = "2018-01-01",
    end: str | None = None,
    forward_horizon: int = 5,
    min_train_months: int = 24,
    test_months: int = 1,
) -> PipelineResult:
    tickers = tickers or DEFAULT_UNIVERSE

    price_panel = load_panel(tickers, start=start, end=end)
    feature_panel = build_feature_panel(price_panel, forward_horizon=forward_horizon)

    dates = feature_panel.index.get_level_values("date")
    folds = generate_folds(
        dates, min_train_months=min_train_months, test_months=test_months, embargo_days=forward_horizon
    )

    all_predictions = []
    last_fold_train = None

    for fold in folds:
        train_df, test_df = split_fold(feature_panel, fold)
        X_train, y_train = train_df[FEATURE_COLUMNS], train_df["forward_return"]
        X_test, y_test = test_df[FEATURE_COLUMNS], test_df["forward_return"]

        result = fit_and_predict_fold(X_train, y_train, X_test, y_test, fold_id=fold.fold_id)
        if result is None:
            continue

        last_fold_train = (X_train, y_train)  # keep most recent successful fold's training data for SHAP

        pred_df = pd.DataFrame(
            {
                "logistic_score": result.logistic_score,
                "xgboost_score": result.xgboost_score,
                "lightgbm_score": result.lightgbm_score,
                "y_true": result.y_true,
            },
            index=result.test_index,
        )
        all_predictions.append(pred_df)

    if not all_predictions:
        raise RuntimeError("No folds produced valid predictions -- check data range and universe size.")

    predictions = pd.concat(all_predictions).reset_index()

    # --- Information Coefficient per model ---
    ic_results = {
        model: compute_ic(predictions, score_col=f"{model}_score")
        for model in ["logistic", "xgboost", "lightgbm"]
    }

    # --- Regime-conditioned IC (trailing 20d realized vol of equal-weighted universe) ---
    market_return = feature_panel.groupby(level="date")["forward_return"].mean()
    market_vol = market_return.rolling(20).std()
    regime_ic_results = {
        model: compute_regime_ic(predictions, market_vol, score_col=f"{model}_score")
        for model in ["logistic", "xgboost", "lightgbm"]
    }

    # --- Backtests: each model's score, plus benchmarks, all through the same engine ---
    backtest_results = {}
    for model in ["logistic", "xgboost", "lightgbm"]:
        backtest_results[model] = run_backtest(
            predictions, score_col=f"{model}_score", strategy_name=model, forward_horizon=forward_horizon
        )
    backtest_results["momentum_benchmark"] = run_backtest(
        momentum_scores(feature_panel), score_col="score", strategy_name="momentum_benchmark",
        forward_horizon=forward_horizon,
    )
    backtest_results["buy_and_hold"] = equal_weight_market_return(feature_panel, forward_horizon=forward_horizon)

    # --- SHAP on the final fold's XGBoost model ---
    if last_fold_train is not None:
        X_train, y_train = last_fold_train
        X_clean = X_train.dropna()
        y_clean = y_train.loc[X_clean.index].dropna()
        X_clean = X_clean.loc[y_clean.index]
        shap_importance = compute_shap_importance(
            X_clean, y_clean, X_clean.sample(min(500, len(X_clean)), random_state=42)
        )
    else:
        shap_importance = pd.DataFrame()

    return PipelineResult(
        predictions=predictions,
        ic_results=ic_results,
        regime_ic_results=regime_ic_results,
        backtest_results=backtest_results,
        shap_importance=shap_importance,
        n_folds_run=len(all_predictions),
    )


if __name__ == "__main__":
    result = run_pipeline(start="2018-01-01", end="2024-01-01")
    print(f"Folds run: {result.n_folds_run}\n")

    print("--- Information Coefficient ---")
    for model, ic in result.ic_results.items():
        print(f"{model}: {ic.summary()}")

    print("\n--- Backtest results ---")
    for name, bt in result.backtest_results.items():
        print(bt.summary())

    print("\n--- SHAP feature importance (top 5) ---")
    print(result.shap_importance.head())
